# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
#test
trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- checkout: self
- task: CopyFiles@2
  inputs:
    Contents: 'request_provider.txt'
    TargetFolder: '$(build.artifactstagingdirectory)'
- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: drop

