# Do not make any changes to this pipeline.
# Any changes to this will be rejected.

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- checkout: self

- task: CopyFiles@2
  inputs:
    Contents: 'request_provider.txt'
    TargetFolder: '$(build.artifactstagingdirectory)'

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: tf_input